// <auto-generated />
using Euriskills.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Euriskills.Migrations
{
    [DbContext(typeof(SzakmaiVersenyzokDbContext))]
    partial class SzakmaiVersenyzokDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Euriskills.Models.Orszag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("orszagNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orszagok");
                });

            modelBuilder.Entity("Euriskills.Models.Szakma", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("szakmaNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Szakmak");
                });

            modelBuilder.Entity("Euriskills.Models.Versenyzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pont")
                        .HasColumnType("INTEGER");

                    b.Property<string>("orszagId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("szakmaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("orszagId");

                    b.HasIndex("szakmaId");

                    b.ToTable("Versenyzok");
                });

            modelBuilder.Entity("Euriskills.Models.Versenyzo", b =>
                {
                    b.HasOne("Euriskills.Models.Orszag", "Orszag")
                        .WithMany("Versenyzok")
                        .HasForeignKey("orszagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Euriskills.Models.Szakma", "Szakma")
                        .WithMany("Versenyzok")
                        .HasForeignKey("szakmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orszag");

                    b.Navigation("Szakma");
                });

            modelBuilder.Entity("Euriskills.Models.Orszag", b =>
                {
                    b.Navigation("Versenyzok");
                });

            modelBuilder.Entity("Euriskills.Models.Szakma", b =>
                {
                    b.Navigation("Versenyzok");
                });
#pragma warning restore 612, 618
        }
    }
}
